### ISSUE TITLE
Some papers to add

### ISSUE THREAD

**Issue by jmyoon1** [hee9joon/Awesome-Diffusion-Models#1]
The Schrodinger bridge problem is a question from statistical physics to find the shortest path that evolves a dynamic system into another system. (I'm not familiar with the concepts, though)
https://arxiv.org/abs/1608.05862

And here are some papers that relate this problem with the diffusion probabilistic model.
https://arxiv.org/abs/2106.01357
http://proceedings.mlr.press/v139/wang21l/wang21l.pdf

**Comment by jmyoon1** [comment]
https://arxiv.org/pdf/2009.05475.pdf
And here is a paper that boosts score-based generative modeling with adversarial robustness.

**Comment by hee9joon** [comment]
Thank you. I added the papers to the list, which will be very helpful for current / future researchers on the field.
